### ISSUE TITLE
DESIGN A NEWS FEED SYSTEM，这个应该翻译成动态比较好

### ISSUE THREAD

**Issue by jsl1992** [Admol/SystemDesign#1]
Feed is the constantly updating list of stories in the middle of your home page. Feed includes status updates, photos, videos, links, app activity and likes from people, Pages and groups that you follow on Facebook.
    动态是位于首页中间不断更新的动态列表。动态包括您在 Facebook 上关注的用户、公共主页和小组发布的状态更新、照片、视频、链接、应用事件和点赞。

**Comment by Admol** [comment]
采纳，感谢 @jsl1992
