### ISSUE TITLE
Goo Job, 请问有第二卷翻译计划么？

### ISSUE THREAD

**Issue by kaimz** [Admol/SystemDesign#13]

**Comment by Admol** [comment]
@kaimz 在考虑，不过最近没啥时间

**Comment by guowei-gong** [comment]
@Admol 我可以帮助您翻译第二卷的部分章节，如果可以，请在 git issues 发布 labels 类 help 的计划

**Comment by Admol** [comment]
@guowei-gong  
感谢，可以查看最新的 issue 。
