### ISSUE TITLE
可能的错别字（语义不明确

### ISSUE THREAD

**Issue by rdzfleo** [Admol/SystemDesign#15]
![image](https://github.com/user-attachments/assets/36818a77-9797-4287-858e-92bc314d9087)
第01章的 数据库复制 一节中的 当前设计**具**有一个数据库，因此不支持故障切换和冗余。  中的“具”字好像是打错了的字，是否应改为“只”字？

**Comment by Admol** [comment]
感谢指出，很细节，已修改。
