### ISSUE TITLE
第九章的那个Figure_9_7的图你配成Table_9_1的图了。

### ISSUE THREAD

**Issue by Jet12138** [Admol/SystemDesign#16]
两年了居然没人发现。。。

**Comment by scydas** [comment]
还在第一章蹦跶呢

**Comment by Admol** [comment]
@Jet12138 感谢指正，说明你认真看了🤣

**Comment by Jet12138** [comment]
![mmexport1731573052843.png](https://github.com/user-attachments/assets/cd1e6ab6-0c2e-47fa-8878-65b9fc5ecd92)

贴一张从道客巴巴上看到的图Figure_9_7

**Comment by Admol** [comment]
@Jet12138   已修复，感谢指正
