### ISSUE TITLE
第一卷/第 12 章 设计一个聊天系统中，有一点描述错误

### ISSUE THREAD

**Issue by 851235550** [Admol/SystemDesign#19]
<img width="729" alt="image" src="https://github.com/user-attachments/assets/d9dab961-0dd6-4812-8ac6-31ab4b10e539">

<br/>
<br/>
<br/>
这里应该是想说：允许同一个账号登录多个 设备 吧？

如果需要，我可以提个 pr 。

**Comment by Admol** [comment]
感谢指正，已修正。
