### ISSUE TITLE
02章有个地方需要讨论一下。

### ISSUE THREAD

**Issue by roamonk** [Admol/SystemDesign#6]
第二章的以下内容有点奇怪吧。

# 讨论点：
“发布2条推文” Vs “查询每秒次数（QPS）”
既然是发布了，那就不是Query，而是transaction吧。
也就是，这不是QPS，而是TPS。

# 原文：
> 示例：估算Twitter的查询量和存储需求
> 请注意，以下数字仅用于本练习，不是 Twitter 的真实数据。
> 
> 假设：
> 
> 每月活跃用户为3亿。
> 50%的用户每天使用 Twitter。
> 用户平均每天发布2条推文。
> 10%的推文包含媒体。
> 数据存储时间为5年。
> 估算： 查询每秒次数（QPS）估计：

**Comment by Admol** [comment]
@roamonk 
你说的很对，其实我也认为这里更应该是使用TPS，而不是QPS。

但是因为是翻译，所以我还是保留了英文版原文的描述，其中明确写的就是QPS。
后续我会在其后面加个备注，标明下应该是理解为 TPS 更好些。

感谢提出疑问，有任何翻译问题可以继续提出哈，有明显错误也可以直接提PR。

**Comment by roamonk** [comment]
好的，谢谢回复。
