### ISSUE TITLE
第八章 LaTex 数学公式， Gitbook 上渲染出错

### ISSUE THREAD

**Issue by lrh3321** [Admol/SystemDesign#9]
https://github.com/Admol/SystemDesign/blob/6b267f4edd564aea03906865de4275042ca21984/CHAPTER%2008%EF%BC%9ADESIGN%20A%20URL%20SHORTENER.md?plain=1#L142-L145

**Comment by Admol** [comment]
@lrh3321  已修复，感谢指正🙏
